### ISSUE TITLE
Don't get images from the web

### ISSUE THREAD

**Issue by Sandotech** [ekrishnachaitanya2004/Dev-blogs#9]
At this moment the blog has a few of posts. So I've created one about Algorithms but at the moment of add an image link to the metadata this wasn't rendered on the web.

So I've had to add it in the `/images` folder, but this is a real issue because at the moment when more users want to create a post with an image they'd have to do the same. There would be a lot of images in the `/images` folder.

So is necessary a feature to solve this problem.

**Comment by ekrishnachaitanya2004** [comment]
**The ImageMod component has been updated to support both local and external image URLs. Key changes include:**

- Detection of external URLs by checking if the src starts with http or https.
- Use of a standard img tag for external URLs to display images.
- Continued use of the Image component for local images.
- Added validation and error logging for local images to ensure proper functionality.

**With these updates, the blog card component now correctly displays images from external sources as well.**
